export const FETCH_USER_COUNT = 'FETCH_USER_COUNT';
export const SET_USER_COUNT = 'SET_USER_COUNT';
export const SET_USER_FAIL = 'SET_USER_FAIL';

export const FETCH_EXPENSE_COUNT = 'FETCH_EXPENSE_COUNT';
export const SET_EXPENSE_COUNT = 'SET_EXPENSE_COUNT';
export const SET_EXPENSE_FAIL = 'SET_EXPENSE_FAIL';

export const FETCH_DEPOSIT_COUNT = 'FETCH_DEPOSIT_COUNT';
export const SET_DEPOSIT_COUNT = 'SET_DEPOSIT_COUNT';
export const SET_DEPOSIT_FAIL = 'SET_DEPOSIT_FAIL';

export const FETCH_EXPENSES = 'FETCH_EXPENSES';
export const SET_EXPENSES_COUNT = 'SET_EXPENSES_COUNT';
export const SET_EXPENSES_FAIL = 'SET_EXPENSES_FAIL';

export const FETCH_EXPENSES_DEPOSITS = 'FETCH_EXPENSES_DEPOSITS';
export const SET_EXPENSES_DEPSOITS_COUNT = 'SET_EXPENSES_DEPSOITS_COUNT';
export const SET_EXPENSES_DEPSOITS_FAIL = 'SET_EXPENSES_DEPSOITS_FAIL';