export const DEPOSIT_FETCH_REQUEST = 'DEPOSIT_FETCH_REQUEST';
export const DEPOSIT_FETCH_SUCCESS = 'DEPOSIT_FETCH_SUCCESS';
export const DEPOSIT_FETCH_FAIL = 'DEPOSIT_FETCH_FAIL';

export const DEPOSIT_ADD_REQUEST = 'DEPOSIT_ADD_REQUEST';
export const DEPOSIT_ADD_SUCCESS = 'ADD_DEPOSIT';
export const DEPOSIT_ADD_FAIL = 'DEPOSIT_ADD_FAIL';

export const DEPOSIT_UPDATE_REQUEST = 'DEPOSIT_UPDATE_REQUEST';
export const DEPOSIT_UPDATE_SUCCESS = 'UPDATE_DEPOSIT';
export const DEPOSIT_UPDATE_FAIL = 'DEPOSIT_UPDATE_FAIL';

export const DEPOSIT_DELETE_REQUEST = 'DEPOSIT_DELETE_REQUEST';
export const DEPOSIT_DELETE_SUCCESS = 'DELETE_DEPOSIT';
export const DEPOSIT_DELETE_FAIL = 'DEPOSIT_DELETE_FAIL';


