export const EXPENSE_FETCH_REQUEST = 'EXPENSE_FETCH_REQUEST';
export const EXPENSE_FETCH_SUCCESS = 'EXPENSE_FETCH_SUCCESS';
export const EXPENSE_FETCH_FAIL = 'EXPENSE_FETCH_FAIL';

export const EXPENSE_ADD_REQUEST = 'EXPENSE_ADD_REQUEST';
export const EXPENSE_ADD_SUCCESS = 'ADD_EXPENSE';
export const EXPENSE_ADD_FAIL = 'EXPENSE_ADD_FAIL';

export const EXPENSE_UPDATE_REQUEST = 'EXPENSE_UPDATE_REQUEST';
export const EXPENSE_UPDATE_SUCCESS = 'UPDATE_EXPENSE';
export const EXPENSE_UPDATE_FAIL = 'EXPENSE_UPDATE_FAIL';

export const EXPENSE_DELETE_REQUEST = 'EXPENSE_DELETE_REQUEST';
export const EXPENSE_DELETE_SUCCESS = 'DELETE_EXPENSE';
export const EXPENSE_DELETE_FAIL = 'EXPENSE_DELETE_FAIL';


